export const clueGenerationPrompt = (mysteryWord: string, otherPlayers: string[]) => `
Give ONE word clue for: "${mysteryWord}"

Other clue-givers in this round: ${otherPlayers.join(', ')}

How obvious your clue should be (1-10): ${Math.floor(Math.random() * 10) + 1}

Rules: No words with the same word, and not the same word in another language. Synonyms are fine though.

THINKING: [Brief reasoning]
CLUE: [One word]
`;

export const guessPrompt = (clues: string[], clueGivers: string[]) => `
Guess the mystery word from these clues: ${clues.join(', ')}

These clues were generated by: ${clueGivers.join(', ')}

THINKING: [Brief reasoning]
GUESS: [One word]
`;

export const SYSTEM_PROMPT = 'You are playing the "Just One" word game. Follow the format exactly.';
